name: Test

on: 
 push:
   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04  

    strategy:
      fail-fast: false  
      matrix:
        ros_distribution:
          - humble  
          
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src 

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          path: ros_ws/src  

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions

      - name: Build the workspace
        run: |
          cd ros_ws
          colcon build --symlink-install

      - name: Run tests
        run: |
          cd ros_ws
          colcon test --packages-select keyboard_teleop 

      - name: Test Results
        run: |
          colcon test-result --verbose

