name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  
    steps:
      - uses: actions/checkout@v2 
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: humble
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-rosdep python3-pip
          pip install rclpy geometry_msgs sshkeyboard pytest 
      - name: Run tests with pytest
        run: |
          cd /root/ros2_ws/src/keyboard_teleop/test
          pytest --maxfail=1 --disable-warnings -q  

